---
version: 2
multicolumn: false
web-width: 200
export-width: 
align: center
float: h!
grid:
  rows: 1
  columns: 1
  grid_elements:
  - url: "/users/230616/articles/293240/master/file/figures/1.5_Kipp1/1.5_Kipp1.png"
    path: figures/1.5_Kipp1/1.5_Kipp1.png
    type: static
    from:
    - 1
    - 1
    to:
    - 1
    - 1
    folder_url: "/users/230616/articles/293240/master/folder/figures/1.5_Kipp1"
